version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: ["python", "app.py"]
    depends_on:
      - dns
  dns:
    build: .
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: ["python", "dns_inventory.py"]
    depends_on:
      - url
  url:
    build: .
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: ["python", "url_analysis.py"]
